"""
FastAPI route definitions.

Endpoints:
  GET  /health    → system status
  POST /ingest    → upload & index a PDF
  POST /query     → ask a question
  GET  /documents → list indexed files
  DELETE /documents/{filename} → remove a document from the index
  GET  /docs      → Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import logging
import shutil
import time
from pathlib import Path

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status

from src.config import settings
from src.ingestion.pipeline import IngestionPipeline
from src.models import (
    DeleteResponse,
    DocumentListResponse,
    HealthResponse,
    IngestionSummary,
    QueryRequest,
    QueryResponse,
)
from src.retrieval.rag_chain import RAGChain

router = APIRouter()
logger = logging.getLogger(__name__)


# ── Dependency helpers ────────────────────────────────────────────────────────

def get_vector_store(request: Request):
    return request.app.state.vector_store


def get_llm_client(request: Request):
    return request.app.state.llm_client


def get_start_time(request: Request) -> float:
    return request.app.state.start_time


# ── GET /health ───────────────────────────────────────────────────────────────

@router.get(
    "/health",
    response_model=HealthResponse,
    summary="System health check",
    tags=["System"],
)
def health(
    vector_store=Depends(get_vector_store),
    llm_client=Depends(get_llm_client),
    start_time: float = Depends(get_start_time),
):
    """Returns model readiness, indexed document count, chunk count, and uptime."""
    return HealthResponse(
        status="ok",
        model=llm_client.llm_model,
        embedding_model=llm_client.embedding_model,
        indexed_documents=len(vector_store.indexed_documents),
        total_chunks=vector_store.total_chunks,
        uptime_seconds=round(time.time() - start_time, 1),
    )


# ── POST /ingest ──────────────────────────────────────────────────────────────

@router.post(
    "/ingest",
    response_model=IngestionSummary,
    status_code=status.HTTP_201_CREATED,
    summary="Ingest a multimodal PDF",
    tags=["Ingestion"],
)
async def ingest(
    file: UploadFile = File(..., description="PDF document to ingest"),
    vector_store=Depends(get_vector_store),
    llm_client=Depends(get_llm_client),
):
    """
    Upload a PDF document. The system will:
    - Extract text, tables, and images
    - Caption images using GPT-4o Vision
    - Embed all chunks using text-embedding-3-small
    - Add to the FAISS vector index

    Returns a summary of chunks ingested by type and processing time.
    """
    # Validate file type
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only PDF files are accepted. Received: " + (file.filename or "unknown"),
        )

    # Save uploaded file to data directory
    data_dir = Path(settings.data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    dest_path = data_dir / file.filename

    try:
        with open(dest_path, "wb") as f:
            shutil.copyfileobj(file.file, f)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to save uploaded file: {exc}",
        )

    # Run ingestion pipeline
    try:
        pipeline = IngestionPipeline(llm_client=llm_client, vector_store=vector_store)
        summary = pipeline.run(dest_path)
    except Exception as exc:
        logger.exception("Ingestion failed for %s", file.filename)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ingestion failed: {exc}",
        )

    return summary


# ── POST /query ───────────────────────────────────────────────────────────────

@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Query the indexed documents",
    tags=["Retrieval"],
)
def query(
    request: QueryRequest,
    vector_store=Depends(get_vector_store),
    llm_client=Depends(get_llm_client),
):
    """
    Ask a natural language question. The system will:
    - Embed your question
    - Retrieve the top-k most relevant chunks (text, table, or image)
    - Generate a grounded answer using GPT-4o
    - Return the answer with source references (file, page, chunk type)
    """
    if vector_store.total_chunks == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No documents indexed. Please POST a PDF to /ingest first.",
        )

    try:
        chain = RAGChain(llm_client=llm_client, vector_store=vector_store)
        return chain.query(request)
    except Exception as exc:
        logger.exception("Query failed: %s", request.question)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Query failed: {exc}",
        )


# ── GET /documents ────────────────────────────────────────────────────────────

@router.get(
    "/documents",
    response_model=DocumentListResponse,
    summary="List indexed documents",
    tags=["Management"],
)
def list_documents(vector_store=Depends(get_vector_store)):
    """Returns the list of PDF filenames currently indexed in the vector store."""
    docs = vector_store.indexed_documents
    return DocumentListResponse(documents=docs, total_documents=len(docs))


# ── DELETE /documents/{filename} ──────────────────────────────────────────────

@router.delete(
    "/documents/{filename}",
    response_model=DeleteResponse,
    summary="Remove a document from the index",
    tags=["Management"],
)
def delete_document(filename: str, vector_store=Depends(get_vector_store)):
    """
    Remove all chunks belonging to the specified PDF from the vector index.
    The physical file in the data/ directory is NOT deleted.
    """
    if filename not in vector_store.indexed_documents:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Document '{filename}' not found in index.",
        )
    removed = vector_store.delete_document(filename)
    return DeleteResponse(
        message=f"Successfully removed {filename} from the index.",
        filename=filename,
        chunks_removed=removed,
    )
